import { Profile } from "./types";

export const MOCK_PROFILES: Profile[] = [
  {
    id: "1",
    name: "Alex Chen",
    age: 20,
    year: "Junior",
    college: "School of Computer Science",
    major: "Computer Science",
    bio: "Building the future one line of code at a time. When I'm not debugging, you can find me at the climbing wall or exploring Pittsburgh's food scene.",
    interests: ["Late night coding", "Rock climbing", "Food adventures", "Hackathons"],
    photos: [],
    lookingFor: "Someone to grab coffee with between classes and debate tabs vs spaces",
    favoriteSpot: "Craig St Coffee",
  },
  {
    id: "2",
    name: "Priya Sharma",
    age: 19,
    year: "Sophomore",
    college: "College of Fine Arts",
    major: "Design",
    bio: "Design major who thinks everything is a design problem - including dating. Let me redesign your love life.",
    interests: ["Art", "Photography", "Coffee addict", "Exploring Pittsburgh"],
    photos: [],
    lookingFor: "A creative soul who appreciates good typography and great conversations",
    favoriteSpot: "Mattress Factory",
  },
  {
    id: "3",
    name: "Jordan Williams",
    age: 21,
    year: "Senior",
    college: "Tepper School of Business",
    major: "Business Administration",
    bio: "Future CEO looking for a co-founder in life. I can pitch anything except my feelings. Tepper by day, DJ by night.",
    interests: ["Entrepreneurship", "Music", "Dancing", "Gym rat"],
    photos: [],
    lookingFor: "Someone ambitious who can keep up with my energy",
    favoriteSpot: "Entropy+",
  },
  {
    id: "4",
    name: "Sam Rodriguez",
    age: 20,
    year: "Junior",
    college: "College of Engineering",
    major: "Mechanical Engineering",
    bio: "I build robots and break hearts (accidentally). Also, I make the best arepas you'll ever try. Buggy driver on weekends.",
    interests: ["Cooking", "Gaming", "Research", "Running"],
    photos: [],
    lookingFor: "Someone patient enough to listen to me talk about thermodynamics",
    favoriteSpot: "Schenley Park",
  },
  {
    id: "5",
    name: "Maya Johnson",
    age: 19,
    year: "Freshman",
    college: "Dietrich College of Humanities & Social Sciences",
    major: "Psychology",
    bio: "Yes, I will psychoanalyze you on the first date. No, I won't tell you what I find. Film buff and aspiring therapist.",
    interests: ["Film", "Reading", "Yoga", "Volunteering"],
    photos: [],
    lookingFor: "Someone emotionally available who can handle deep conversations at 2am",
    favoriteSpot: "Phipps Conservatory",
  },
  {
    id: "6",
    name: "Chris Park",
    age: 21,
    year: "Senior",
    college: "School of Computer Science",
    major: "Artificial Intelligence",
    bio: "Training neural networks by day, training for the marathon by night. I promise I have hobbies outside of ML. Okay, most of them are ML-adjacent.",
    interests: ["Late night coding", "Running", "Anime", "Study groups"],
    photos: [],
    lookingFor: "Someone who won't judge me for talking to my GPU like it's a pet",
    favoriteSpot: "The Fence",
  },
  {
    id: "7",
    name: "Olivia Martinez",
    age: 20,
    year: "Sophomore",
    college: "Mellon College of Science",
    major: "Physics",
    bio: "Looking for someone with gravitational pull. I study the universe and still can't figure out dating apps. Stargazing enthusiast.",
    interests: ["Hiking", "Photography", "Board games", "Research"],
    photos: [],
    lookingFor: "A fellow nerd who gets excited about the night sky",
    favoriteSpot: "Frick Park",
  },
  {
    id: "8",
    name: "Tyler Washington",
    age: 22,
    year: "Senior",
    college: "College of Fine Arts",
    major: "Drama",
    bio: "Drama major who promises to only be dramatic on stage. Shakespeare geek, improv comedian, and surprisingly good cook.",
    interests: ["Dancing", "Cooking", "Thrift shopping", "Film"],
    photos: [],
    lookingFor: "My scene partner for life - someone spontaneous and witty",
    favoriteSpot: "Randyland",
  },
  {
    id: "9",
    name: "Nina Patel",
    age: 19,
    year: "Freshman",
    college: "School of Computer Science",
    major: "Human-Computer Interaction",
    bio: "Making tech more human, one wireframe at a time. Bubble tea enthusiast. Will judge your app's UX on the first date.",
    interests: ["Art", "Coffee addict", "K-pop", "Exploring Pittsburgh"],
    photos: [],
    lookingFor: "Someone whose personality has as good a UX as their smile",
    favoriteSpot: "Craig St Coffee",
  },
  {
    id: "10",
    name: "Marcus Davis",
    age: 21,
    year: "Junior",
    college: "College of Engineering",
    major: "Electrical & Computer Engineering",
    bio: "Hardware nerd in a software world. I built my own keyboard and I will talk about it unprompted. Basketball every Saturday morning.",
    interests: ["Gaming", "Basketball", "Hackathons", "Late night coding"],
    photos: [],
    lookingFor: "Someone who appreciates a good soldering job and terrible puns",
    favoriteSpot: "The Cut",
  },
  {
    id: "11",
    name: "Lily Zhang",
    age: 20,
    year: "Sophomore",
    college: "Dietrich College of Humanities & Social Sciences",
    major: "Economics",
    bio: "I can explain supply and demand but not why I'm still single. Avid reader, amateur baker, and professional procrastinator.",
    interests: ["Reading", "Cooking", "Board games", "Volunteering"],
    photos: [],
    lookingFor: "Someone who brings positive externalities to my life",
    favoriteSpot: "Pamela's Diner",
  },
  {
    id: "12",
    name: "Daniel Kim",
    age: 22,
    year: "Senior",
    college: "Mellon College of Science",
    major: "Mathematics",
    bio: "The probability of us matching is higher than you think. I see beauty in proofs and pizza. State champion chess player.",
    interests: ["Board games", "Tennis", "Study groups", "Music"],
    photos: [],
    lookingFor: "Someone irrational enough to date a math major",
    favoriteSpot: "Carnegie Museum",
  },
];
